package com.gamesShop.model;
// Generated Aug 12, 2017 11:51:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Availability generated by hbm2java
 */
@Entity
@Table(name="availability"
    ,catalog="games_data"
)
public class Availability  implements java.io.Serializable {


     private Integer availabilityId;
     private String availability;
     private Set<Game> games = new HashSet<Game>(0);

    public Availability() {
    }

	
    public Availability(String availability) {
        this.availability = availability;
    }
    public Availability(String availability, Set<Game> games) {
       this.availability = availability;
       this.games = games;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="availability_id", unique=true, nullable=false)
    public Integer getAvailabilityId() {
        return this.availabilityId;
    }
    
    public void setAvailabilityId(Integer availabilityId) {
        this.availabilityId = availabilityId;
    }

    
    @Column(name="availability", nullable=false, length=45)
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="availability")
    public Set<Game> getGames() {
        return this.games;
    }
    
    public void setGames(Set<Game> games) {
        this.games = games;
    }

    @Override
    public String toString() {
        return  availability ;
    }




}


