package com.gamesShop.model;
// Generated Aug 12, 2017 11:51:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GameNames generated by hbm2java
 */
@Entity
@Table(name="game_names"
    ,catalog="games_data"
)
public class GameNames  implements java.io.Serializable {


     private Integer gameNamesId;
     private Producer producer;
     private String name;
     private Set<Game> games = new HashSet<Game>(0);

    public GameNames() {
    }

	
    public GameNames(Producer producer, String name) {
        this.producer = producer;
        this.name = name;
    }
    public GameNames(Producer producer, String name, Set<Game> games) {
       this.producer = producer;
       this.name = name;
       this.games = games;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="game_names_id", unique=true, nullable=false)
    public Integer getGameNamesId() {
        return this.gameNamesId;
    }
    
    public void setGameNamesId(Integer gameNamesId) {
        this.gameNamesId = gameNamesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="producer_id", nullable=false)
    public Producer getProducer() {
        return this.producer;
    }
    
    public void setProducer(Producer producer) {
        this.producer = producer;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gameNames")
    public Set<Game> getGames() {
        return this.games;
    }
    
    public void setGames(Set<Game> games) {
        this.games = games;
    }

    @Override
    public String toString() {
        return  name ;
    }




}


