package com.gamesShop.model;
// Generated Aug 12, 2017 11:51:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producer generated by hbm2java
 */
@Entity
@Table(name="producer"
    ,catalog="games_data"
)
public class Producer  implements java.io.Serializable {


     private Integer producerId;
     private String name;
     private Set<Game> games = new HashSet<Game>(0);
     private Set<GameNames> gameNameses = new HashSet<GameNames>(0);

    public Producer() {
    }

	
    public Producer(String name) {
        this.name = name;
    }
    public Producer(String name, Set<Game> games, Set<GameNames> gameNameses) {
       this.name = name;
       this.games = games;
       this.gameNameses = gameNameses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="producer_id", unique=true, nullable=false)
    public Integer getProducerId() {
        return this.producerId;
    }
    
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producer")
    public Set<Game> getGames() {
        return this.games;
    }
    
    public void setGames(Set<Game> games) {
        this.games = games;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producer")
    public Set<GameNames> getGameNameses() {
        return this.gameNameses;
    }
    
    public void setGameNameses(Set<GameNames> gameNameses) {
        this.gameNameses = gameNameses;
    }

    @Override
    public String toString() {
        return  name ;
    }





}


