package com.gamesShop.model;
// Generated Aug 12, 2017 11:51:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="games_data"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String lastname;
     private String country;
     private String email;
     private String password;
     private int accountAccess;

    public User() {
    }

    public User(String name, String lastname, String country, String email, String password, int accountAccess) {
       this.name = name;
       this.lastname = lastname;
       this.country = country;
       this.email = email;
       this.password = password;
       this.accountAccess = accountAccess;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="lastname", nullable=false, length=45)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="country", nullable=false, length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="account_access", nullable=false)
    public int getAccountAccess() {
        return this.accountAccess;
    }
    
    public void setAccountAccess(int accountAccess) {
        this.accountAccess = accountAccess;
    }




}


